// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BellOutlined: typeof import('@ant-design/icons-vue')['BellOutlined']
    ClassItem: typeof import('./components/ClassItem.vue')['default']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
    LogoutOutlined: typeof import('@ant-design/icons-vue')['LogoutOutlined']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    PlusCircleOutlined: typeof import('@ant-design/icons-vue')['PlusCircleOutlined']
    RandomIcon: typeof import('./components/RandomIcon.vue')['default']
    RichTextEditor: typeof import('./components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./components/Scrollbar.vue')['default']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    Shadow: typeof import('./components/Shadow.vue')['default']
    StarFilled: typeof import('@ant-design/icons-vue')['StarFilled']
    StarOutlined: typeof import('@ant-design/icons-vue')['StarOutlined']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
